### ISSUE TITLE
Make "Software Links" easier to see

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#14]
One feedback I heard so far is that it took the user a minute to figure out that "Software Links" is where he can access his plugins. We should simplify this and make each link into their own menu items instead of hiding them in a dropdown. There's nothing else in the toolbar, so we have space for them. Something like this:

![image](https://user-images.githubusercontent.com/1692600/202781141-f25bea1b-c5bd-4444-9613-5f72f3954575.png)

What do you think?

**Comment by KTS915** [comment]
Sure
