### ISSUE TITLE
Hide empty tabs on developer profiles

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#19]
We should consider hiding empty tabs on developer profiles.

For example, plugins and themes would be hidden in this example:
![image](https://user-images.githubusercontent.com/1692600/203859521-6e1f4289-284f-4ac0-b1cc-503a8bfd53e4.png)

**Comment by xxsimoxx** [comment]
What do you think about this solution?
<img width="477" alt="image" src="https://user-images.githubusercontent.com/29772709/203989508-61ca09dd-bd4b-4ffd-8c74-ead451bc7c0f.png">

**Comment by viktorix** [comment]
Thanks. That's a good alternative.

**Comment by viktorix** [comment]
I'm re-opening this issue. Got some feedback from azurecurve:
> I think the empty tab doesn't look great; it suggests the the developer also does themes.
