### ISSUE TITLE
Check what it means to switch plugin repo

### ISSUE THREAD

**Issue by smileBeda** [ClassicPress/directory#2]
If we implement our own plugin repo and remove WP repo, all current installs will stop getting updates from WP

we know that there has been and there is a practice of using WP plugins in cp
Thus perhaps “a bundled” repo would need to be analyzed?

right now many sites miss updates from plugins they use which aren’t anymore “compatible” with cp
Removing WP repo at all will also remove updates for those who are actually compatible

**Comment by xxsimoxx** [comment]
Maybe I missed something, but as I can recall the idea was to **add** CP repo, not to remove WP repo.

**Comment by smileBeda** [comment]
If that’s the case we can close here!
Yes I think this is a must, unfortunately, at least the updates (maybe we could disable install)

**Comment by joyously** [comment]
There is already a mechanism for themes. If you go into the Customizer, there is a button named "Change" next to the name of the Active Theme. When you click that, you see all the local themes but the sidebar has a choice of showing local or WP repo. It should be fairly simple to add another entry there, for CP.
This can be the way it works for plugins also, although probably not in the Customizer.

![Customize Classicly Pressed – Another great website powered by ClassicPress-15](https://user-images.githubusercontent.com/7957680/131697190-bc013233-f9d6-4b30-82c1-6370083d13d0.jpg)

**Comment by nylen** [comment]
We will not be able to remove the WP repo for the foreseeable future, at least until ClassicPress has a mature ecosystem.

A good portion of the work in integrating the new directory will be making sure that plugins can be managed from both repositories while keeping it clear which plugin came from which source, and how and from where any updates will be installed.

Anyway I agree this issue can be closed, in favor of creating more specific tasks in the main repository for the integration into core.
