### ISSUE TITLE
Align download/more info links to the bottom of the card

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#25]
![image](https://user-images.githubusercontent.com/1692600/204710521-3eeeb24f-f75f-464e-b77f-ec1fbff3062e.png)

Right now, all cards have equal heights and descriptions of various lengths. This pushes download/more info links up and down, it's not uniform. There is no consistency.

I'd like to propose aligning them to the bottom of the card with a few HTML/CSS changes to make them look unform and consistent. You can see an example of one in the screenshot above.

One additional suggestion, we should truncate text better to make it more consistent. Maybe even using CSS to hide text to keep it consistent to 3-4 lines.

**Comment by ghost** [comment]
i found a solution for this you'll need to target `<p>` and add `min-height:  125px`
![image](https://user-images.githubusercontent.com/11844123/204869493-ab5a125e-f4be-4a04-8f75-5a84b8dd0260.png)

**Comment by xxsimoxx** [comment]
Thank you @benlumia007 ! Tomorrow i'll open a PR to fix this!

**Comment by ghost** [comment]
```
.software-grid .hentry p {
   margin: 1em 0;
   min-height: 8em;
}
```
should be correct, if we just target just `p` it moves everything single page down.

**Comment by ghost** [comment]
Please note that a PR has been created! #27.

**Comment by viktorix** [comment]
@benlumia007 @xxsimoxx do you think we should truncate descriptions to 3 or 4 lines? So they appear more uniform. Using CSS `line-clamp` would do the trick.

**Comment by ghost** [comment]
@viktorix 
I don't know really since I never try or use `line-clamp`. Maybe @xxsimoxx can answer that.
