### ISSUE TITLE
GitHub slugs and directory slugs

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#36]
I noticed that directory post slugs are generated by the post title as it normally would, but the actual slug used in the API is based on the repo slug:
https://staging-directory.classicpress.net/plugins/smtp/
```
"meta": {
"current_version": "2.1.0",
"git_provider": "github",
"requires_cp": "1",
"download_link": "https://github.com/azurecurve/azrcrv-smtp/releases/download/v2.1.0/azrcrv-smtp.zip",
"requires_php": "7.4",
"slug": "azrcrv-smtp",
"developer_name": "azurecurve",
"category_names": "Tools",
"category_slugs": "tools"
}
```

Should we use the actual slug in the URL too? A reviewer could verify this during review process when publishing software.

**Comment by xxsimoxx** [comment]
For now the page slug is different from the plugin slug and as you said it reflects the plugin name.
As example every CodePotent plugin have a name different from the plugin slug (Shortcodes Everywhere has `codepotent-shortcodes-everywhere`).
I prefer having the `URL` matching the name but that's not so important for me.

**Comment by viktorix** [comment]
One problem I noticed, the current search doesn't work with API slugs. So if I search for "azrcrv-smtp", it won't find the plugin. We either need to be consistent with slugs or figure out a way to make API slugs searchable.

**Comment by viktorix** [comment]
For the issue of searching for plugins using API slug, I was able to fix it by indexing slugs using Relevanssi. See issue #37.

**Comment by xxsimoxx** [comment]
This is also relative to #24 and #23.

We are using `Search & Filter` plugin. It's a lot of time they are promising v. 3.

The actual functions of this plugin are not 100% what we need, so we will have to decide:
1. Wait in the hope that v. 3 comes out with what we need
2. Find out an alternative
3. Fork the plugin and add what we need.

**Comment by viktorix** [comment]
Are we using `Search and Filter` plugin for APIs? Or is it just that, for searching?

**Comment by xxsimoxx** [comment]
Just for searching.
The REST API endpoint is this:
`https://staging-directory.classicpress.net/wp-json/wp/v2/plugins?byslug=azrcrv-smtp`

**Comment by viktorix** [comment]
Thanks for this. Actually, we're not modifying the plugin but core search. I disabled the plugin and the API still returns correct plugin by slug.

**Comment by viktorix** [comment]
@xxsimoxx do we agree that keeping directory post slug and Github slug separate/different is the way to go now? So we can close this issue.

**Comment by xxsimoxx** [comment]
For me there are no problems in keeping the slugs different.
