### ISSUE TITLE
Metadata for GitHub

### ISSUE THREAD

**Issue by ghost** [ClassicPress/directory#74]
So i found out that when I was working on my own GitHub communication using API for my own personal site. I found that the `Last Updated` has an issue where it sometimes trying to retrieved information, it will display 54 years ago! Please see the following 
![Screenshot 2023-06-20 at 10 08 49 AM](https://github.com/ClassicPress/Directory/assets/11844123/b6ad449f-5032-4273-b0e1-fa335ebc1f0c)

Please see if we can either fix this or set a check if the response to the API has limited or timeout!

**Comment by ghost** [comment]
We should close this if this was already been fixed.

**Comment by viktorix** [comment]
Should be fixed.
