### ISSUE TITLE
Empty dropdown in search form

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#9]
**Describe the bug**
An empty select dropdown in plugins search form.

**To Reproduce**
1. Go to Plugins page and look at the search form

**Expected behavior**
No empty dropdowns.

**Screenshots**
![image](https://user-images.githubusercontent.com/1692600/202758914-2ecaecce-4936-4c8e-80f8-3f74e8581c43.png)

**Comment by xxsimoxx** [comment]
It was empty because no tags were present.
Now it correctly shows search by tag.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/29772709/204536952-aa27ed25-2872-4aa2-bd91-9dc6d6e6ed5f.png">
